### ISSUE TITLE
Error, if there is a missing samplerate/channels variant for any filter

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#10]
I think, it would be nice, if an error is reported, if there is a missing variant for any filter.
E.g. filter "left" has variants "left-44100-2.wav" & "left-48000-2.wav" and filter "right" has only one variant "right-44100-2.wav".
Then there would be a warning, that "right-48000-2.wav" is missing.

**Comment by HEnquist** [comment]
To implement this the validator has to loop through all filters twice. 
On the first loop, it would check for files with all possible samplerates. This would result in a list of rates there is at least one file for. Then it would loop trough the filters again, and warn for those that don't support all those rates. 
I'm not conviced this should be in the validator. It's already complicated enough, and I prefer to keep it as simple as possible to limit the number of mistakes.
I would suggest putting something in the backend, that gives a list of rates to the frontend. This list could then be shown in a tooltip or something:
44100: ok
48000: X
88200: ok
96000: X
etc (and ok should then be a checkmark).

**Comment by JWahle** [comment]
Okay, I'll try an implementation in the backend.
