### ISSUE TITLE
Only one error reported for devices and each filter

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#5]
[This config](https://github.com/HEnquist/pycamilladsp-plot/files/6417996/multiple_errors.yml.zip) has:
- 2 errors on the devices page (silence_threshold: 10 and silence_timeout: -10)
- 2 errors for "New filter 1": (negative Q and freq)
- 2 errors for "New filter 2": (negative Q and freq)

However, only 3 errors are reported.
One for the devices section and one for each filter.
This is how the JSON looks in the GUI (but I checked with the debugger, the error list in the backend also has just 3 errors):
```
{
  "devices": { "silence_threshold": "10 is greater than the maximum of 0.0"},
  "filters": {
    "New Filter 1": {"parameters": {"freq": "-1000 is less than or equal to the minimum of 0.0"}},
    "New Filter 2": {"parameters": {"freq": "-1000 is less than or equal to the minimum of 0.0"}}
  }
}
```

**Comment by HEnquist** [comment]
I found a solution to this, will implement tomorrow!

**Comment by HEnquist** [comment]
Should work now!

**Comment by JWahle** [comment]
Errors everywhere - soooo beautiful ;)
