### ISSUE TITLE
CamillaValidator().get_config() removes variables from filter file names

### ISSUE THREAD

**Issue by JWahle** [HEnquist/pycamilladsp-plot#9]
[This config with variables in filter file names](https://github.com/HEnquist/pycamilladsp-plot/files/6446188/filter-name-replacements.yml.zip) does not contain any variables when loaded into the GUI.
All variables should remain present, when loaded in the GUI.

**Comment by HEnquist** [comment]
There are now separate functions to get a config with all tokens left (get_config) and with all tokens replaced as well as abslute paths inserted for coefficient files (get_processed_config).

**Comment by JWahle** [comment]
Works for me - nice.
